2025-08-21 19:13:57,166 - INFO - üöÄ Starting section optimisation pipeline
2025-08-21 19:13:57,166 - INFO - üóÇ Results stored in: C:\Users\samea\Desktop\geometry_tools\n_sections\results\optimisation\20250821_191357
2025-08-21 19:13:57,168 - ERROR - ‚ùå Failed to load optimisation limits: [Errno 2] No such file or directory: 'C:\\Users\\samea\\Desktop\\geometry_tools\\n_sections\\blade_optimisation_limits\\target_section_properties.csv'
Traceback (most recent call last):
  File "c:\Users\samea\Desktop\geometry_tools\n_sections\main_optimise.py", line 69, in main
    limits_df = pd.read_csv(limits_csv).set_index("filename")
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samea\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samea\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samea\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samea\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\Users\samea\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\samea\\Desktop\\geometry_tools\\n_sections\\blade_optimisation_limits\\target_section_properties.csv'
